"A datetime string with format `Y-m-d H:i:s`, e.g. `2018-05-23 13:43:32`."
scalar DateTime @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\DateTime")

type User {
    id: ID!
    name: String!
    username: String!
    email: String!
    posts: [Post!]! @hasMany
    created_at: DateTime!
}

type Post {
    id: ID!
    body: String!
    author: User! @belongsTo(relation: "user")
    created_at: DateTime!
}

type Query {
    "Fetch a single user by their unique username."
    userProfile(username: String! @eq): User @find

    "A paginated list of all posts across the platform, newest first."
    feed: [Post!]! @paginate(defaultCount: 15)
}

type Mutation {
    "Create a new post."
    createPost(input: CreatePostInput! @spread): Post @create
}

input CreatePostInput {
    user_id: ID!
    body: String! @rules(apply: ["required", "string", "min:20", "max:280"])
}
